
[core]
modal = true

[ui]
font-family = "JetBrainsMono Nerd Font Mono"
hover-font-family = "JetBrainsMono Nerd Font Mono"

[editor]
font-family = "JetBrainsMono Nerd Font Mono"
autosave-interval = 100
inlay-hint-font-family = "JetBrainsMono Nerd Font Mono"
error-lens-font-family = "JetBrainsMono Nerd Font Mono"
completion-lens-font-family = "JetBrainsMono Nerd Font Mono"

[terminal]
font-family = "JetBrainsMono Nerd Font Mono"
