
[core]
modal = true

[ui]
font-family = "JetBrainsMonoNL Nerd Font Mono"
hover-font-family = "JetBrainsMonoNL Nerd Font Mono"

[editor]
font-family = "JetBrainsMonoNL Nerd Font Mono"
autosave-interval = 500
inlay-hint-font-family = "JetBrainsMonoNL Nerd Font Mono"
error-lens-font-family = "JetBrainsMonoNL Nerd Font Mono"
completion-lens-font-family = "JetBrainsMonoNL Nerd Font Mono"
format-on-autosave = true

[terminal]
font-family = "JetBrainsMonoNL Nerd Font Mono"
