[build]
target = "x86_64-unknown-linux-musl"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld"
]
[profile.lto]
codegen-units = 1 # Better optimization
debug = false # Inherits from release so should actually do nothing but whatever
inherits = "release"
lto = true # link time optimization
strip = true # smaller binary
