rustc_ast = { path = "/home/gramar/.rustup/toolchains/nightly-2025-04-02-x86_64-unknown-linux-gnu/lib/rustlib/rustc-src/rust/compiler/rustc_ast", optional = true}
rustc_span = { path = "/home/gramar/.rustup/toolchains/nightly-2025-04-02-x86_64-unknown-linux-gnu/lib/rustlib/rustc-src/rust/compiler/rustc_span", optional = true}
