local bufnr = vim.api.nvim_get_current_buf()
vim.keymap.set("n", "<leader>rem", function()
    vim.cmd.RustLsp("expandMacro")
end, { silent = true, buffer = bufnr })
vim.keymap.set("n", "<leader>ree", function()
    vim.cmd.RustLsp({ "explainError", "cycle" })
end, { silent = true, buffer = bufnr })
vim.keymap.set("n", "<leader>rrd", function()
    vim.cmd.RustLsp({ "renderDiagnostic", "cycle" })
end, { silent = true, buffer = bufnr })
vim.keymap.set("n", "<leader>rha", function()
    vim.cmd.RustLsp({ "hover", "actions" })
end, { silent = true, buffer = bufnr })
vim.keymap.set("n", "<leader>roc", function()
    vim.cmd.RustLsp("openCargo")
end, { silent = true, buffer = bufnr })
vim.keymap.set("n", "<leader>cdc", function()
    vim.cmd(":botright terminal cargo deny check")
end, { silent = true, buffer = bufnr })
vim.keymap.set("n", "<leader>ccr", function()
    vim.cmd(":botright terminal cargo clippy")
end, { silent = true, buffer = bufnr })
