require "pluginit.nvim-treesitter"
require "pluginit.nvim-tree"
require "pluginit.telescope"
require "pluginit.lualine"
require "pluginit.toggleterm"
require "pluginit.aerial"
require "pluginit.rustaceanvim"
require "pluginit.pylsp"
require "pluginit.zls"
require "pluginit.diffview"
require "pluginit.cmp"
require "pluginit.catppuccin"

