[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMonoNL NF" }

[keyboard]
bindings = [
    { key = "F", mods = "Control|Shift", action = "ReceiveChar" }
]


[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
