[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
normal = { family = "JetBrainsMonoNL NF" }
size = 12

[keyboard]
bindings = [
    { key = "F", mods = "Control|Shift", action = "ReceiveChar" }
]


[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
